version: '3.1'

services:

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: catalogdb
      MYSQL_USER: develop
      MYSQL_PASSWORD: develop
    ports:
      - 3306:3306 
  